<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hwt9053_driver</name>
  <version>0.0.0</version>
  <description>HWT9053-485 AHRS IMU 센서 ROS2 드라이버 (sensor_msgs/Imu 퍼블리시)</description>
  <maintainer email="yju@todo.todo">yju</maintainer>
  <license>TODO</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>

  <!-- pymodbus 는 pip 패키지라 rosdep 키가 없음 -> pip install pymodbus 로 별도 설치 -->
  <exec_depend>python3-serial</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
